image: maven:latest

services:
  - docker:dind

variables:
  MAVEN_CLI_OPTS: "--batch-mode -Ddockerfile.username=$CI_REGISTRY_USER -Ddockerfile.password=$CI_REGISTRY_PASSWORD"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - build

before_script:
  - curl -sSL https://get.docker.com/ | sh
  - apt-get update && apt-get install --no-install-recommends -y openjfx && apt-get clean && rm -f /var/lib/apt/lists/*_dists_*
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-master:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS install
    - mvn $MAVEN_CLI_OPTS dockerfile:build dockerfile:push -pl StreamProcessor,SubscriberCluster,SensorCluster,BenchmarkController -Ddocker-registry="$CI_REGISTRY_IMAGE"
  tags:
    - ILT
