version: '2'

services:
  sensorclusterLow:
    image: fraunhoferiosb/sensorcluster:0.0.1-SNAPSHOT
    environment:
      - NAME=SensorCluster_Low
      - BASE_URL=http://10.56.4.54:8080/FROST-Server/v1.0/
      - RESULT_URL=https://frost-server-hzg.docker01.ilt-dmz.iosb.fraunhofer.de/v1.0
      - BROKER=tcp://10.56.4.54:1883
      - SESSION=0001
      - WORKERS=10
      - SENSORS=50
      - PERIOD=1000

  sensorclusterMedium:
    image: fraunhoferiosb/sensorcluster:0.0.1-SNAPSHOT
    environment:
      - NAME=SensorCluster_Medium
      - BASE_URL=http://10.56.4.54:8080/FROST-Server/v1.0/
      - RESULT_URL=https://frost-server-hzg.docker01.ilt-dmz.iosb.fraunhofer.de/v1.0
      - BROKER=tcp://10.56.4.54:1883
      - SESSION=0001
      - WORKERS=10
      - SENSORS=50
      - PERIOD=1000

  sensorclusterHigh:
    image: fraunhoferiosb/sensorcluster:0.0.1-SNAPSHOT
    environment:
      - NAME=SensorCluster_High
      - BASE_URL=http://10.56.4.54:8080/FROST-Server/v1.0/
      - RESULT_URL=https://frost-server-hzg.docker01.ilt-dmz.iosb.fraunhofer.de/v1.0
      - BROKER=tcp://10.56.4.54:1883
      - SESSION=0001
      - WORKERS=10
      - SENSORS=50
      - PERIOD=1000

  subscriberClusterLow:
    image: fraunhoferiosb/subscribercluster:0.0.1-SNAPSHOT
    environment:
      - NAME=SubscriberCluster_Low
      - BASE_URL=http://10.56.4.54:8080/FROST-Server/v1.0/
      - RESULT_URL=https://frost-server-hzg.docker01.ilt-dmz.iosb.fraunhofer.de/v1.0
      - BROKER=tcp://10.56.4.54:1883
      - SESSION=0001
      - COVERAGE=0

  subscriberClusterMedium:
    image: fraunhoferiosb/subscribercluster:0.0.1-SNAPSHOT
    environment:
      - NAME=SubscriberCluster_Medium
      - BASE_URL=http://10.56.4.54:8080/FROST-Server/v1.0/
      - RESULT_URL=https://frost-server-hzg.docker01.ilt-dmz.iosb.fraunhofer.de/v1.0
      - BROKER=tcp://10.56.4.54:1883
      - SESSION=0001
      - COVERAGE=0

  subscriberClusterHigh:
    image: fraunhoferiosb/subscribercluster:0.0.1-SNAPSHOT
    environment:
      - NAME=SubscriberCluster_High
      - BASE_URL=http://10.56.4.54:8080/FROST-Server/v1.0/
      - RESULT_URL=https://frost-server-hzg.docker01.ilt-dmz.iosb.fraunhofer.de/v1.0
      - BROKER=tcp://10.56.4.54:1883
      - SESSION=0001
      - COVERAGE=0

  analyticsClusterLow:
    image: fraunhoferiosb/analyticscluster:0.0.1-SNAPSHOT
    environment:
      - NAME=Analytics_Low
      - BASE_URL=http://10.56.4.54:8080/FROST-Server/v1.0/
      - RESULT_URL=https://frost-server-hzg.docker01.ilt-dmz.iosb.fraunhofer.de/v1.0
      - BROKER=tcp://10.56.4.54:1883
      - SESSION=0001
      - ANALYTIC_JOBS=0
      - ANALYTIC_LOOPS=1000
      - JITTER=5
      - PERIOD=1000
      - WORKERS=10

  analyticsClusterMedium:
    image: fraunhoferiosb/analyticscluster:0.0.1-SNAPSHOT
    environment:
      - NAME=Analytics_Medium
      - BASE_URL=http://10.56.4.54:8080/FROST-Server/v1.0/
      - RESULT_URL=https://frost-server-hzg.docker01.ilt-dmz.iosb.fraunhofer.de/v1.0
      - BROKER=tcp://10.56.4.54:1883
      - SESSION=0001
      - ANALYTIC_JOBS=0
      - ANALYTIC_LOOPS=1000
      - JITTER=5
      - PERIOD=1000
      - WORKERS=10

  analyticsClusterHigh:
    image: fraunhoferiosb/analyticscluster:0.0.1-SNAPSHOT
    environment:
      - NAME=Analytics_High
      - BASE_URL=http://10.56.4.54:8080/FROST-Server/v1.0/
      - RESULT_URL=https://frost-server-hzg.docker01.ilt-dmz.iosb.fraunhofer.de/v1.0
      - BROKER=tcp://10.56.4.54:1883
      - SESSION=0001
      - ANALYTIC_JOBS=0
      - ANALYTIC_LOOPS=1000
      - JITTER=5
      - PERIOD=1000
      - WORKERS=10
