version: '2'

services:
  sensorclusterLow:
    image: fraunhoferiosb/sensorcluster:latest
    environment:
      - NAME=SensorCluster_Low
      - BASE_URL=${FROST_SERVER}
      - RESULT_URL=${FROST_SERVER}
      - BROKER=${MQTT_BROKER}
      - SESSION=0001
      - WORKERS=10
      - SENSORS=50
      - PERIOD=8000

  sensorclusterMedium:
    image: fraunhoferiosb/sensorcluster:latest
    environment:
      - NAME=SensorCluster_Medium
      - BASE_URL=${FROST_SERVER}
      - RESULT_URL=${FROST_SERVER}
      - BROKER=${MQTT_BROKER}
      - SESSION=0001
      - WORKERS=10
      - SENSORS=50
      - PERIOD=4000

  sensorclusterHigh:
    image: fraunhoferiosb/sensorcluster:latest
    environment:
      - NAME=SensorCluster_High
      - BASE_URL=${FROST_SERVER}
      - RESULT_URL=${FROST_SERVER}
      - BROKER=${MQTT_BROKER}
      - SESSION=0001
      - WORKERS=10
      - SENSORS=50
      - PERIOD=1000

  subscriberClusterLow:
    image: fraunhoferiosb/subscribercluster:latest
    environment:
      - NAME=SubscriberCluster_Low
      - BASE_URL=${FROST_SERVER}
      - RESULT_URL=${FROST_SERVER}
      - BROKER=${MQTT_BROKER}
      - SESSION=0001
      - COVERAGE=5

  subscriberClusterMedium:
    image: fraunhoferiosb/subscribercluster:latest
    environment:
      - NAME=SubscriberCluster_Medium
      - BASE_URL=${FROST_SERVER}
      - RESULT_URL=${FROST_SERVER}
      - BROKER=${MQTT_BROKER}
      - SESSION=0001
      - COVERAGE=10

  subscriberClusterHigh:
    image: fraunhoferiosb/subscribercluster:latest
    environment:
      - NAME=SubscriberCluster_High
      - BASE_URL=${FROST_SERVER}
      - RESULT_URL=${FROST_SERVER}
      - BROKER=${MQTT_BROKER}
      - SESSION=0001
      - COVERAGE=30

  analyticsClusterLow:
    image: fraunhoferiosb/analyticscluster:latest
    environment:
      - NAME=Analytics_Low
      - BASE_URL=${FROST_SERVER}
      - RESULT_URL=${FROST_SERVER}
      - BROKER=${MQTT_BROKER}
      - SESSION=0001
      - ANALYTIC_JOBS=01
      - ANALYTIC_LOOPS=1000
      - JITTER=5
      - PERIOD=5000
      - WORKERS=2

  analyticsClusterMedium:
    image: fraunhoferiosb/analyticscluster:latest
    environment:
      - NAME=Analytics_Medium
      - BASE_URL=${FROST_SERVER}
      - RESULT_URL=${FROST_SERVER}
      - BROKER=${MQTT_BROKER}
      - SESSION=0001
      - ANALYTIC_JOBS=2
      - ANALYTIC_LOOPS=1000
      - JITTER=5
      - PERIOD=3000
      - WORKERS=5

  analyticsClusterHigh:
    image: fraunhoferiosb/analyticscluster:latest
    environment:
      - NAME=Analytics_High
      - BASE_URL=${FROST_SERVER}
      - RESULT_URL=${FROST_SERVER}
      - BROKER=${MQTT_BROKER}
      - SESSION=0001
      - ANALYTIC_JOBS=3
      - ANALYTIC_LOOPS=1000
      - JITTER=5
      - PERIOD=1000
      - WORKERS=10
