name: Maven Build

on:
  push:
    branches:
      - master
      - develop
      - develop-*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Cache maven repository
      uses: actions/cache@v2.1.6
      with:
        path: |
          ~/.m2/repository
          ~/.sonar/cache
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Checkout Source
      uses: actions/checkout@v2.4.0

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11

    - name: Build with Maven
      run: |
        mvn -B install -Dmaven.javadoc.skip=true

    - name: Build Docker Images
      run: |
        mvn -B dockerfile:build -pl StreamProcessor,SubscriberCluster,SensorCluster,BenchmarkController,AnalyticsCluster

    - name: Push Docker Image - Tagged Commit
      if: startsWith(github.ref, 'refs/tags/')
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        export DOCKER_TAG=$(mvn -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec -q)
        echo "Tagging and Pushing ${DOCKER_TAG}"
        mvn -B dockerfile:tag@tag-version -pl StreamProcessor,SubscriberCluster,SensorCluster,BenchmarkController,AnalyticsCluster
        mvn -B dockerfile:push@push-version -Ddockerfile.useMavenSettingsForAuth=true -pl StreamProcessor,SubscriberCluster,SensorCluster,BenchmarkController,AnalyticsCluster --settings maven-ci-settings.xml

    - name: Push Docker Images - Master branch
      if: github.ref == 'refs/heads/master'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        export DOCKER_TAG=$(mvn -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec -q)
        echo "Tagging and Pushing ${DOCKER_TAG}"
        mvn -B dockerfile:tag@tag-version -pl StreamProcessor,SubscriberCluster,SensorCluster,BenchmarkController,AnalyticsCluster
        mvn -B dockerfile:push@push-version -Ddockerfile.useMavenSettingsForAuth=true -pl StreamProcessor,SubscriberCluster,SensorCluster,BenchmarkController,AnalyticsCluster --settings maven-ci-settings.xml
        echo "Pushing latest"
        mvn -B dockerfile:push@push-latest -Ddockerfile.useMavenSettingsForAuth=true -pl StreamProcessor,SubscriberCluster,SensorCluster,BenchmarkController,AnalyticsCluster --settings maven-ci-settings.xml

    - name: Push Docker Image - Other branch
      if: startsWith(github.ref, 'refs/heads/develop')
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        export version=$(mvn -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec -q)
        export DOCKER_TAG=${GITHUB_REF:11}-${version}
        echo "Tagging and Pushing ${DOCKER_TAG}"
        mvn -B dockerfile:tag@tag-version -pl StreamProcessor,SubscriberCluster,SensorCluster,BenchmarkController,AnalyticsCluster
        mvn -B dockerfile:push@push-version -Ddockerfile.useMavenSettingsForAuth=true -pl StreamProcessor,SubscriberCluster,SensorCluster,BenchmarkController,AnalyticsCluster --settings maven-ci-settings.xml
